def task_exception():
    raise Exception
